# Generated by Django 3.2.5 on 2021-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210707_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
