# Generated by Django 3.2.5 on 2021-07-09 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_habit_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habitrecord',
            name='unique_records',
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='habitrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='unique_records'),
        ),
    ]
